### PR TITLE
Support for Google Sheet & Excel 365 Data via Cloudstitch 

### PR DESCRIPTION
**Pull request by eob**
Hi guys! 

**Love** this plugin and wanted to wire it up to support cloud spreadsheets via Cloudstitch, which provides a single API for accessing spreadsheet data, among other things.

Tried my best to match your coding style (which is impressively consistent), though I anticipate you'll have a few requests if this is something you'd like to eventually accept. Happy to make them.

### CODE REVIEW

**Comment by nitrada** [comment]
Thanks! We're going to check it out!

**Comment by nitrada** [comment]
Hey @eob, I have checked out your Cloudstitch plugin and found it pretty cool. The ease to set up data, instead of writing JSON is impressive. 

As I wrote in this article (https://medium.com/sketch-app-sources/designing-with-meaningful-data-5456b40e172e?source=linkShare-345ea3b8842a-1486889395) I'm not convinced it's always the best goal to make a designer's life more easy and convenient. Working with real data, and digging through APIs and JSON structure makes them more data literate and I'm convinced that's important. 

On the other hand I have learned to appreciate spreadsheets as a great design tool to for example design for different contexts at the same time by using formula for let's say dimensions and proportions. So for sure, working with data in spreadsheets also adds to a designer's data structures education. 

But I would expect to be able to also work with more complex data structures: how can I populate a spreadsheet with two dimensions (as in a real data table)? Or how can I use a spreadsheet for nested data?

It's not well documented, but Data Populator has the capability to populate from a two dimensional CSV. The structure you need to prepare for that within Sketch is very restrictive, or strict and we're not so happy about his. But we were able to show it's possible. Can you imagine investigating here? I think this would be so much better if you could leapfrog the whole CSV process and just connect to a service like Cloudstitch. 

So what I think is that I'd like to include Cloudstitch features into Data Populator. But I would expect it to become more sophisticated in the long run. 

Something else I figured where I see room for improvement: we went down the path of using local JSON and introducing the Presets feature because we found that populating performance is so much better. That's why for now, we avoided something like "Populate from URL". Images can be URLs, but this already slows down the process.

If we integrate Cloudstitch features into Data Populator, I think there's still room for a Cloudstitch plugin you could offer your customers as a direct link to Sketch. I would just expect it to become more individual then – not have all the other Data Populator features, it's own readme etc. It could become a bit of a maintenance nightmare otherwise. 

What do you think?

**Comment by nitrada** [comment]
check out these files to see a demo of the 'Populate Table' command as it's currently implemented:

[PopulateTable.zip](https://github.com/preciousforever/sketch-data-populator/files/769281/PopulateTable.zip)

**Comment by eob** [comment]
Hi @nitrada -- thanks so much for such a thoughtful response!

All of this sounds great to us.

About data:

* We actually support hierarchical data via spreadsheets! It's super easy, but poorly documented -- only on [this blog post](https://medium.com/@edwardbenson/hacking-hierarchical-joins-into-spreadsheets-rails-style-b022b1a11c3c)
* I'l take a look at the zip file and we would love to try to work in support for the style of data table you all support as well. Will get back to you.

About forking the plugin:

We would love to contribute code to your project and we're happy to trim ours down so that it's specific to us---not an alternative/rebranded version of yours. We forked-and-extended as we did just for the sake of time savings. We're for a product launch now, but in a week or two we'll probably ping you again for some advice about keeping/removing different pieces.

Let us know if there's anything you'd like changed in terms of the PR -- happy to do a bit of code revision to get something great.

**Comment by nitrada** [comment]
Will check out the blog post!

I think – apart from maintenance – the biggest issue with overlapping commands is if you use Sketch Runner – what you get is duplicate commands (same command names, descriptions and icons!). We'll look into the PR!

The biggest issue I have with our "populate table" (apart from the need to manually export the data via TSV, which Cloudstitch fixes! :) is that the elements to be populated are determined by a very strict layer structure: you need certain names, levels and order of things. That's pretty restrictive. I think it would be much better if this would be done by their x/y coordinates on the artboard. What do you think?

**Pull request closed without merging**
